version: '2'

services:
    web:
        build: ./web
        container_name: toolbox-web
        image: toolbox-web
        ports:
            - ${APP_PORT}:80
            - ${APP_PORT_SSL}:443
        volumes:
            - ${APP_DIR}:/home/app:ro
        links:
            - php
        network_mode: bridge

    php:
        build: ./php
        container_name: toolbox-php
        image: toolbox-php
        links:
            - db
        volumes:
            - ${APP_DIR}:/home/app:cached
        network_mode: bridge
        working_dir: /home/app

    db:
        build: ./dbserver
        container_name: toolbox-db
        image: toolbox-db
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ${APP_DB}:/var/lib/mysql
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        network_mode: bridge
